### ISSUE TITLE
1.21.1

### ISSUE THREAD

**Issue by seetch** [By1337/BAuction#5]
```[21:22:16 INFO]: seetch5 issued server command: /ah sell 10 64
[21:22:16 ERROR]: [BAuction] An error occurred while executing the command
java.lang.ExceptionInInitializerError: null
        at BAuction-1.3.3-ru.jar/org.by1337.bauction.util.auction.TagUtil.getTags(TagUtil.java:65) ~[BAuction-1.3.3-ru.jar:?]
        at BAuction-1.3.3-ru.jar/org.by1337.bauction.db.kernel.SellItem.<init>(SellItem.java:211) ~[BAuction-1.3.3-ru.jar:?]
        at BAuction-1.3.3-ru.jar/org.by1337.bauction.command.impl.SellCmd.execute(SellCmd.java:69) ~[BAuction-1.3.3-ru.jar:?]
        at BLib-1.2.jar/org.by1337.blib.command.CommandExecutor.execute(CommandExecutor.java:21) ~[BLib-1.2.jar:?]
        at BLib-1.2.jar/org.by1337.blib.command.Command.process(Command.java:156) ~[BLib-1.2.jar:?]
        at BLib-1.2.jar/org.by1337.blib.command.Command.process(Command.java:110) ~[BLib-1.2.jar:?]
        at BAuction-1.3.3-ru.jar/org.by1337.bauction.Main.onCommand0(Main.java:362) ~[BAuction-1.3.3-ru.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: unsupported version
        at BAuction-1.3.3-ru.jar/org.by1337.bauc.util.ParsePDCTagsMagager.<clinit>(ParsePDCTagsMagager.java:36) ~[BAuction-1.3.3-ru.jar:?]
        ... 35 more
        
        > ver
[21:23:19 INFO]: Checking version, please wait...
[21:23:19 INFO]: Current Purpur Version: 1.21.1-2326-4f2fe31 (MC: 1.21.1)*
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.20.6-2233-0d6766e (MC: 1.20.6)
> pl
[21:23:22 INFO]: Paper Plugins: (0):
[21:23:22 INFO]: Bukkit Plugins: (22):
[21:23:22 INFO]:  - AutoMine, BAuction, BLib, ccInstantRespawn, Citizens, CMI, CMILib, DecentHolograms, ExecutableItems, FastAsyncWorldEdit
[21:23:22 INFO]:  kLib, LuckPerms, packetevents, PlaceholderAPI, PlayerPoints, PlugManX, ProAntiTab, SCore, TAB, Vault
[21:23:22 INFO]:  WorldGuard, Worlds```

**Comment by fazilovairat20-alt** [comment]
смог исправить?
